### ISSUE TITLE
SettingsGenerator Segmentation fault

### ISSUE THREAD

**Issue by rozgo** [VertexStudio/simbotic-gams#2]
```
sim@vertex:/sim/AirSim$ ./build_debug/output/bin/SettingsGenerator
Segmentation fault (core dumped)
```

**Comment by racsoraul** [comment]
Solved with PR #3.

It was caused when **SIMBOTIC_ROOT** env variable wasn't found, which is the case inside the Docker container. The current usage of SettingsGenerator requires to have access to the Simbotic project.

Now it'll exit execution if env variable isn't found:
```
sim@raul:/sim/AirSim$ ./build_debug/output/bin/SettingsGenerator 
Environment variable SIMBOTIC_ROOT doesn't exist!
Exiting
```
